Comments system, marks
lazuta/new-mgz pull request #2
Opened 2020-01-22 22:11 UTC by lazuta

1. Изменил некоторые связи
2. Добавил вывод комментариев, отображение оценки

2020-02-15 18:59 UTC, AlekseyKrupsky requested changes

2020-02-15 18:59 UTC, AlekseyKrupsky commented on app/Article.php
> +        return $this->belongsTo('App\User', 'user_id', 'id');
Здесь правильно поправил!

2020-02-15 18:59 UTC, AlekseyKrupsky commented on app/Http/Controllers/ArticlesController.php
> +        $comments = Comment::where('reviews_id', $id)->orderBy('created_at','DESC')->get();
Тут сразу у меня вопрос, тебе в метод приходит $id - это id от Article. Почему он же используется для выборки комментов при поиске по reviews_id. reviews_id == article_id ? Или неправильно названо поле и должно быть
$comments = Comment::where('article_id ', $id) ?
Ну и такое можно вообще при наличии связей в модели вынести в отдельный метод.
В модели Article добавляешь 
```
    public function comments()
    {
        return $this->hasMany('App\Comment');
    }
```
И потом в контроллере можно вызывать так:
$article = Article::find($id);
$comments = $article->comments()->orderBy('created_at','DESC')->get();
Такое сработает если в модели артикл есть поле article_id тогда ларавел все сам свяжет

2020-02-15 18:59 UTC, AlekseyKrupsky commented on app/Http/Controllers/ArticlesController.php
> +        return view('article.layout', ['article' => $article], ['comments' => $comments]);
Вроде можно в один массив пихать ['article' => $article, 'comments' => $comments]

2020-02-15 18:59 UTC, AlekseyKrupsky commented on app/Http/Controllers/ArticlesController.php
> +
Тут можно сделать еще одним способом:
```
$user = Auth::user();
$user->createReviewer($request['description'], $article->id);
```

В модели User:

```
function createReviewer($desc, $art_id) {
$this->reviewer()->create([
'description' => desc,
'article_id' => art_id
]);
}
```

2020-02-15 18:59 UTC, AlekseyKrupsky commented on app/Http/Controllers/CommentsController.php
> +        $approved = NULL;
в чем разница?

2020-02-15 18:59 UTC, AlekseyKrupsky commented on app/Http/Controllers/CommentsController.php
> +        if (!empty($request['approved']) || $request['approved'] != 2)
!==, если в $request['approved'] будет true то условие будет верным и появится не очевидная ошибка

2020-02-15 18:59 UTC, AlekseyKrupsky commented on app/Http/Controllers/CommentsController.php
> +            'user_id' => Auth::id()
то же не понятно почему убрана запятая, это твоя IDE так сделала?

2020-02-15 18:59 UTC, AlekseyKrupsky commented on app/Http/Controllers/CommentsController.php
> -
Зачем пустой метод?

2020-02-15 18:59 UTC, AlekseyKrupsky commented on app/Http/Controllers/CommentsController.php
>          $comment = Comment::create([
Переменная не используется, так же как и $validatedData.

2020-02-15 18:59 UTC, AlekseyKrupsky commented on app/Http/Controllers/CommentsController.php
>              $approved = $request['approved'];
Не стоит сохранять значение в переменную если дальше оно использует только 1 раз, лучше так и оставить и потом написать:
`'approved' => $request['approved'],`

2020-02-15 18:59 UTC, AlekseyKrupsky commented on app/Http/Controllers/CommentsController.php
И здесь тоже можно было бы перенести логику в модель, например:
$user->addComment($request->all()).

И тогда в модели User пишем

```
function addComment($data) {
$comment = $this->comments()->create($data);
return $comment; // это если он там нужен
}
```

Просто мне кажется что код который отвечает за сохранение\создание\извлечение записей в БД должен находится в модели. Но это уже как удобнее. Просто как вариант на всякий случай

2020-02-15 18:59 UTC, AlekseyKrupsky commented on app/Reviewer.php
>  {
Блин почему Reviewer ??? Для меня это как тот кто проводит ревью
Было бы логичнее Review и таблица reviews

2020-02-15 18:59 UTC, LordAlexey commented on resources/views/comment/create.blade.php
> +                <option>Требутеся доработка</option>
Должно быть значение value, пусть например, -1. Просто если значение не стоит это на бэке равноценно тому что оно не отправлено, нет определенности

2020-02-15 18:59 UTC, LordAlexey commented on app/Http/Controllers/CommentsController.php
> +        Reviewer::find($request['id'])->update(['mark' => $request['mark']]);
Не вижу проверки mark на корректные значения

2020-02-15 18:59 UTC, LordAlexey commented on app/RewiewerType.php
> +        return $this->hasMany('App\Atricle', 'id');
Atricle или все-таки Article?

2020-02-15 18:59 UTC, LordAlexey commented on resources/views/article/layout.blade.php
>                      @foreach ($article->file as $item)
Если стоит debbuger посмотри сколько будет запросов в базу на этой странице. Использовать функцию из модели в цикле в шаблоне не лучшая идея, но пока пускай так и будет

2020-02-15 18:59 UTC, LordAlexey commented on resources/views/article/layout.blade.php
> +                        @else
Разве не предусмотрено значение на "плохо" ?

2020-02-15 18:59 UTC, LordAlexey commented on resources/views/article/layout.blade.php
> +                        @elseif ($comment->approved == 0)
Возможно в данном случае если $comment->approved будет содержать null то выполнится это условие, хотя ты сравниваешь с нулем

2020-02-15 18:59 UTC, LordAlexey commented on app/Http/Controllers/ArticlesController.php
> +    public function storege(Request $request)
Что за новое слово "storege" ?

2020-02-15 18:59 UTC, LordAlexey commented on app/Http/Controllers/ArticlesController.php
> +            'description' => $request['description']
Что-то я не понимаю что здесь происходит. Почему мы обновляем Review, когда обновляем Article? Ведь Article может обновлять только автор, почему обновляется описание отзывов?

2020-02-15 18:59 UTC, LordAlexey commented on app/Http/Controllers/UserController.php
> +    public function approve(Request $request, $id)
Если что можно писать так approve(Request $request, User $user)

потом в переменной $user будет объект и можно применять методы
$user->->update(['reviewer' => true]);

2020-02-15 18:59 UTC, LordAlexey commented on app/Http/Controllers/UserController.php
> +    public function denied(Request $request, $id)
Метод называется denied а мы в нем ставим юзеру роль автора

2020-02-15 18:59 UTC, LordAlexey commented on app/User.php
>      public function reviewer()
про это название я писал, что объект должен называться  Review а не Reviewer. Иначе здесь reviewer и метод сверху reviewers, они же не одни и те же объекты возвращают

2020-02-15 18:59 UTC, LordAlexey commented on resources/views/auth/register.blade.php
> +                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail адрес') }}</label>
слово "адрес" лучше убрать

2020-02-15 18:59 UTC, LordAlexey commented on routes/web.php
> +    Route::post('/storege', 'ArticlesController@store')->name('article.store');
storege ? Новое слово?

2020-02-15 18:59 UTC, LordAlexey commented on routes/web.php
> +    Route::get('edit/{id}', 'ArticlesController@edit')->name('article.edit');
почему сверху со слешами вначале пути, а здесь нет? если работает и так и так, надо все равно писать одинаково везде

2020-02-15 18:59 UTC, LordAlexey commented on app/Http/Controllers/ReviewersController.php
> +        $articles = Article::where('user_id', Auth::id())->get();
Что за метод, зачем он? Он ничего не возвращает

2020-02-15 18:59 UTC, LordAlexey commented on database/migrations/2019_11_10_100005_create_files_table.php
> +            $table->string('pdf_path');
зачем это поле? почему нельзя путь к pdf записать в поле file_path?

2020-02-15 18:59 UTC, LordAlexey commented on resources/views/users/appointment.blade.php
> +                        @foreach ($reviewers as $key=>$reviewer)
добавь пробелы $key => $reviewer

2020-02-15 18:59 UTC, LordAlexey commented on resources/views/comment/review.blade.php
> +    <form action="" method="POST" >
не задан урл куда отправлять форму

2020-02-15 18:59 UTC, LordAlexey commented on resources/views/comment/review.blade.php
> +    <h5 class="card-title">Добавить ревьюирование</h5>
Интересное слово "ревьюирование", ты думаешь преподы знают что это такое?

2020-02-15 18:59 UTC, LordAlexey commented on app/Http/Controllers/ArticleReviewController.php
> +            $path = '/storage/' . $request->file('file')->store('files', 'public');
sprintf

2020-02-15 18:59 UTC, LordAlexey commented on resources/views/article/layout.blade.php
> +                        Auth::user()->reviewer)
```
@elseif(
Auth::user()->role == "reviewer" 
&& Auth::user()->reviewer
)
```
Хотя, блин, сам не знаю как тут по стандарту будет

2020-02-15 18:59 UTC, LordAlexey commented on resources/views/article/layout.blade.php
>                  @if(Auth::user()->role == "corrector")
пробел после if

2020-02-19 09:00 UTC, lazuta commented on resources/views/comment/review.blade.php
> +    <h5 class="card-title">Добавить ревьюирование</h5>
Уточнил, знают)

2020-02-20 19:19 UTC, lazuta commented on resources/views/comment/review.blade.php
> +    <h5 class="card-title">Добавить ревьюирование</h5>
Создать рецензию

2020-03-13 11:44 UTC, merged